---
title: "Ngram Browser"
---

Use the controls to display a yearly count of the relative frequency of a term or terms as found in the abstracts of the State Papers: Stuart. The term can either be the original spelling (case has been ignored), or the lemmatized word.

It accepts regular expressions. For instance, to search for all words ending in **king** use the search term `.*king` For more on the regular expressions you can use see [here](https://stringr.tidyverse.org/articles/regular-expressions.html).

To add several terms, use `|` to separate the words, and `^` and `$` to indicate the beginning and end of each word, except for the beginning of the first and the end of the last. For example, to get results for both **ship** and **war** use `ship\$\|\^war`.

Choose between a chart displaying the frequency and one displaying the rank using a log scale.

Use of this to look for trends should be with caution. The abstracts come from the Calendars of State Papers, and some periods and series have more extended abstracts than others. Lemmatization uses a modern dictionary and may not give accurate results.

<iframe src="https://networkingarchives.shinyapps.io/stuart_ngram_browser" width="1000px" height="700px" frameBorder="0">

</iframe>
