---
title: "Team"
---

Faculty of History, University of OxfordProfessor Howard Hotson, Fellow and Tutor in Modern History, Professor of Early Modern Intellectual History
St. Anne’s College, University of Oxford

Dr Ruth Ahnert, Senior Lecturer in Renaissance Studies
School of English and Drama, Queen Mary University of London

Dr Sebastian Ahnert, Gatsby Career Development Fellow, Sainsbury Laboratory/Cavendish Laboratory, Fellow and Director of Studies
King’s College, University of Cambridge

Miranda Lewis, Editor, Early Modern Letters Online
Cultures of Knowledge, History Faculty, University of Oxford

Dr Esther van Raamsdonk, Project Associate, British Academy Fellow, Warwick University

Dr Philip Beeley, Project Research Fellow, Faculty of History, University of Oxford

Dr Yann Ryan, Project Research Fellow, School of English and Drama, Queen Mary University of London

# Past Members
Matthew Wilcoxson, Research Software Engineer
Oxford eResearch Centre, University of Oxford

Arno Bosse, Digital Project Manager
Cultures of Knowledge, History Faculty, University of Oxford